# Generated by Django 4.2.5 on 2023-11-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(help_text='Максимум 200 символів', max_length=200, verbose_name='Категорія'),
        ),
    ]
