# Generated by Django 4.2.5 on 2023-11-30 20:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_alter_category_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='articleimage',
            options={'verbose_name': 'Article Photo', 'verbose_name_plural': 'Article Photos'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category for publication', 'verbose_name_plural': 'Categories for publications'},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='app_blog.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_page',
            field=models.BooleanField(default=False, help_text='Show on the main page', verbose_name='Main'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of publication'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(unique_for_date='pub_date', verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Maximum 250 characters', max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_blog.article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.ImageField(upload_to='photos', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='title',
            field=models.CharField(blank=True, help_text='Maximum 250 characters', max_length=250, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(help_text='Maximum 250 characters', max_length=250, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', verbose_name='Slug'),
        ),
    ]
